#!/bin/bash
#
# adapted from z3bra -- 2014-01-21
# http://blog.z3bra.org/2014/01/images-in-terminal.html

test -z "$1" && exit

W3MIMGDISPLAY="/usr/lib/w3m/w3mimgdisplay"
FILENAME=$1
FONTH=13 # Size of one terminal row
FONTW=9  # Size of one terminal column
COLUMNS=`tput cols`
LINES=`tput lines`

if [ `echo "$FILENAME" | grep "tps\?://"` ] ; then
    cd /tmp
    wget -q "$FILENAME" -O "/tmp/tmp-icar"
    FILENAME="/tmp/tmp-icar"
    TMP=true
else
    TMP=false
fi

read width height <<< `echo -e "5;$FILENAME" | $W3MIMGDISPLAY`

max_width=$(($FONTW * $COLUMNS))
max_height=$(($FONTH * $(($LINES - 4)))) # substract one line for prompt

if [ $width -gt $max_width ]; then
    height=$(($height * $max_width / $width))
    width=$max_width
fi
if [ $height -gt $max_height ]; then
    width=$(($width * $max_height / $height))
    height=$max_height
fi

tput cup $(($height/$FONTH)) 0
w3m_command="0;1;0;0;$width;$height;;;;;$FILENAME\n4;\n3;"

echo -e $w3m_command|$W3MIMGDISPLAY

if $TMP ; then
    rm $FILENAME
fi
